default: &default
  adapter: <%= ENV['DB_ADAPTER'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test

production:
  <<: *default
